# -*- coding: utf-8 -*-
"""av02_grupo_Van_Rossum_Delivery.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wPQXr6NlatdoGlH88Fmqqg7cUCfGlncw

# Projeto de Algoritmos - Avaliação 2

Alunos: CARLOS ALBERTO DE OLIVEIRA SANTOS e MAXSUEL CEZÁRIO RODRIGUES

# Ideia: Criação de aplicativo de delivery

<A ideia inicial é a criação de um app dinâmico para entrega de comida >

# Implementação
"""

cardapio = ["(1)-X-burguer R$ 10,00 ", " (2)-Hot-dog R$ 8,00 ", "(3)-pizza R$ 12,00 "]
selecionado = 0
pedido = []
qtd_pedido =[]
preco = [10, 8, 12]
quantidade =0
valor_pedido = []
forma_de_pagamento = ["(1)Cartão de Crédito", "(2)Cartão de Débito", "(3)PIX", "(4)Picpay"]
algo_mais = 0
confirma = "s"
sel_forma_pgt = 0
remover = "s"
nova_qtd_pedido = 0
qtd_removida = 0


print("Olá seja bem vindo, segue o nosso cardápio")
print("")
print(cardapio)
print("")


selecionado = int(input("Escolha o nº da opção desejada >> "))
print(cardapio[selecionado-1])
quantidade = int(input("Digite a quantidade desejada>> "))
print("Você escolheu",  cardapio[selecionado-1]," - ", quantidade, "unidade(s)")
confirma = input(("Confirma o pedido ? (s) ou (n) "))

while confirma == "n":
  print("")
  print(cardapio)
  print("")
  selecionado = int(input("Escolha o nº da opção desejada >> "))
  print(cardapio[selecionado-1])
  quantidade = int(input("Digite a quantidade desejada>> "))
  print("Você escolheu",  cardapio[selecionado-1]," - ", quantidade, "unidade(s)")
  confirma = input(("Confirma o pedido ? (s) ou (n) "))

if confirma == "s":
  print("Pedido Registrado")
  pedido.append(cardapio[selecionado-1])
  qtd_pedido.append(quantidade)
  valor_pedido.append(preco[selecionado-1]*quantidade)
  remover = input("Deseja editar a quantidade do pedido? (s) ou (n) ")

if remover == "s":
  qtd_removida = int(input("Digite a quantidade a ser removida  "))
  nova_qtd_pedido = qtd_pedido[0]-qtd_removida
  qtd_pedido.remove(quantidade)
  qtd_pedido.append(nova_qtd_pedido)
  valor_pedido = []
  valor_pedido.append(preco[selecionado-1]*nova_qtd_pedido)


algo_mais = input("Deseja algo mais ?? (s) ou (n) ")

while algo_mais == "s":
    print("")
    print(cardapio)
    print("") 
    selecionado = int(input("Escolha o nº da opção desejada >> "))
    print(cardapio[selecionado-1])
    quantidade = int(input("Digite a quantidade desejada>> "))
    print("Você escolheu",  cardapio[selecionado-1]," - ", quantidade, "unidade(s)")
    confirma = input(("Confirma o pedido ? (s) ou (n) "))
    if confirma == "s":
      print("Pedido Registrado")
      pedido.append(cardapio[selecionado-1])
      qtd_pedido.append(quantidade)
      valor_pedido.append(preco[selecionado-1]*quantidade)
      remover = input("Deseja editar a quantidade do pedido? (s) ou (n) ")

      if remover == "s":
          qtd_removida = int(input("Digite a quantidade a ser removida  "))
          nova_qtd_pedido = qtd_pedido[0]-qtd_removida
          qtd_pedido.remove(quantidade)
          qtd_pedido.append(nova_qtd_pedido)
          valor_pedido = []
          valor_pedido.append(preco[selecionado-1]*nova_qtd_pedido)



    algo_mais = input("Deseja algo mais ?? (s) ou (n) ")


print("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-")
print( "Seu pedido foi confirmado", qtd_pedido," unidade(s)", pedido)
print("Valor total do pedido R$", sum(valor_pedido))
print("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-")
print("")
print("")


print("Qual a forma de pagamento ?")
print(forma_de_pagamento)
sel_forma_pgt = int(input("Digite o número da opção desejada >>> "))

if sel_forma_pgt == 1:
  print("Pagamento no crédito confirmado")

elif sel_forma_pgt == 2:
  print("Pagamento no débito confirmado")

elif sel_forma_pgt == 3:
  print("Pagamento no PIX confirmado")

else:
  print("Pagamento PICPAY")